language: java
sudo: false

jdk:
- oraclejdk8
addons:
  apt:
    packages:
      - oracle-java8-installer

install: true
script: mvn verify -B -e -V

matrix:
  fast_finish: true

cache:
  directories:
    - '$HOME/.m2/repository'

notifications:
  email: false
